# Generated by Django 6.0.6 on 2026-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(help_text='MT5 trade ticket number', unique=True)),
                ('symbol', models.CharField(help_text='e.g. EURUSD, XAUUSD', max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-open_time'],
            },
        ),
    ]
