# Generated by Django 6.0.6 on 2026-06-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_id', models.CharField(default='default', max_length=50)),
                ('environment', models.CharField(default='demo', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Snapshot',
                'verbose_name_plural': 'Account Snapshots',
            },
        ),
    ]
